/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testezinho;

import testezinho.model.Pessoa;
import testezinho.model.Professor;

public class App {


    public static void main(String[] args) throws Exception {
        
    Professor npc = new Professor("Claudinho", 58);
    npc.setNome("Pafoca");
    	System.out.println(npc.getNome());
    	
    }
}
